{% set name = "atomai" %}
{% set version = "0.7.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/atomai-{{ version }}.tar.gz
  sha256: 79425ee60e76c5c558f9ef5cbe391c1ee8444f14c05679d3f2980d2b9359141b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pytorch >=1.0.0
    - numpy >=1.18.5
    - matplotlib-base >=3.4
    - scipy >=1.3.0
    - scikit-learn >=0.22.1
    - scikit-image >=0.16.2
    - opencv >=4.1.0
    - networkx >=2.5
    - mendeleev <=0.6.1
    - torchvision >=0.13.0
    - progressbar2 >=3.38.0
    - gpytorch >=1.9.1

test:
  imports:
    - atomai
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pycroscopy/atomai/
  summary: Deep and machine learning for atom-resolved data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
